### PR TITLE
Fix Makefile to work correctly

### PR DESCRIPTION
**Pull request by indiesquidge**
You moved things to the reference folder which broke the Makefile. This fixes that.

### CODE REVIEW

**Comment by indiesquidge** [comment]
Are you sure you'll pulling all of the changes from the `queue` branch? We haven't been committing to master since we started the queue.

I would delete the whole repo, fork it again, set the upstream to be Ian's repo, and then pull from the upstream queue branch to get the most recent version of what we're working on. Then you can try out the differences we've made in the PRs to test if it works. I can't replicate the issue when I make, so I'm not sure what it is. Let me know if you keep having the issue afterwards.

**Comment by indiesquidge** [comment]
I would make sure that everything is up to date with Ian's branches before checking on the PR's.

**Comment by ianks** [comment]
@dawsonbotsford It looks like you might be missing the `pthread` lib.

**Comment by ianks** [comment]
PR looks good :+1:

**Pull request merged**
